// elements-data.js - Complete periodic table data including all 118 elements

// Helper functions for property calculations
function getCategoryColor(category) {
    return `var(--${category})`;
}

function getColorForValue(value, min, max) {
    if (value === null || value === undefined) {
        return '#e0e0e0';
    }
    
    // Normalize the value between 0 and 1
    const normalized = (value - min) / (max - min);
    
    // Convert to RGB using a gradient from blue to yellow to red
    let r, g, b;
    
    if (normalized < 0.5) {
        // Blue to yellow gradient for lower half
        const t = normalized * 2;
        r = Math.round(255 * t);
        g = Math.round(255 * t);
        b = Math.round(255 * (1 - t));
    } else {
        // Yellow to red gradient for upper half
        const t = (normalized - 0.5) * 2;
        r = 255;
        g = Math.round(255 * (1 - t));
        b = 0;
    }
    
    return `rgb(${r}, ${g}, ${b})`;
}

// Periodic table data
const elements = [
    { number: 1, symbol: 'H', name: 'Hydrogen', mass: 1.008, category: 'nonmetal', electronegativity: 2.20, atomicRadius: 53, ionizationEnergy: 13.598, meltingPoint: -259.16, boilingPoint: -252.87, electronConfig: '1s¹', shells: [1], hybridization: ['None or 1s'], applications: ['Fuel source', 'Ammonia production', 'Oil refining', 'Hydrogenation of oils', 'Rocket fuel'] },
    { number: 2, symbol: 'He', name: 'Helium', mass: 4.0026, category: 'noble-gas', electronegativity: null, atomicRadius: 31, ionizationEnergy: 24.587, meltingPoint: -272.2, boilingPoint: -268.93, electronConfig: '1s²', shells: [2], hybridization: ['None'], applications: ['Cooling superconducting magnets', 'Lifting gas', 'Pressurizing liquid fuel rockets', 'Shielding gas for welding', 'Deep-sea diving gas mixtures'] },
    { number: 3, symbol: 'Li', name: 'Lithium', mass: 6.94, category: 'alkali-metal', electronegativity: 0.98, atomicRadius: 167, ionizationEnergy: 5.392, meltingPoint: 180.54, boilingPoint: 1342, electronConfig: '[He] 2s¹', shells: [2, 1], hybridization: ['None'], applications: ['Lithium-ion batteries', 'Ceramics and glass', 'Lubricating greases', 'Mood stabilizing medication', 'Alloys with aluminum and magnesium'] },
    { number: 4, symbol: 'Be', name: 'Beryllium', mass: 9.0122, category: 'alkaline-earth', electronegativity: 1.57, atomicRadius: 112, ionizationEnergy: 9.323, meltingPoint: 1287, boilingPoint: 2470, electronConfig: '[He] 2s²', shells: [2, 2], hybridization: ['sp', 'sp²', 'sp³'], applications: ['X-ray windows', 'Aerospace components', 'Nuclear reactors', 'Computer parts', 'Precision instruments'] },
    { number: 5, symbol: 'B', name: 'Boron', mass: 10.81, category: 'metalloid', electronegativity: 2.04, atomicRadius: 87, ionizationEnergy: 8.298, meltingPoint: 2076, boilingPoint: 3927, electronConfig: '[He] 2s² 2p¹', shells: [2, 3], hybridization: ['sp²', 'sp³'], applications: ['Glass and ceramics', 'Detergents and bleaches', 'Semiconductors', 'Neutron absorber in nuclear reactors', 'Agriculture (micronutrient)'] },
    { number: 6, symbol: 'C', name: 'Carbon', mass: 12.011, category: 'nonmetal', electronegativity: 2.55, atomicRadius: 67, ionizationEnergy: 11.260, meltingPoint: 3550, boilingPoint: 4027, electronConfig: '[He] 2s² 2p²', shells: [2, 4], hybridization: ['sp', 'sp²', 'sp³'], applications: ['Structural element in all organic compounds', 'Steel production', 'Carbon fiber', 'Graphite in pencils', 'Diamond in cutting tools'] },
    { number: 7, symbol: 'N', name: 'Nitrogen', mass: 14.007, category: 'nonmetal', electronegativity: 3.04, atomicRadius: 56, ionizationEnergy: 14.534, meltingPoint: -210.1, boilingPoint: -195.79, electronConfig: '[He] 2s² 2p³', shells: [2, 5], hybridization: ['sp', 'sp²', 'sp³'], applications: ['Fertilizer production', 'Refrigerant', 'Food preservation', 'Explosives manufacturing', 'Inert atmosphere for chemical reactions'] },
    { number: 8, symbol: 'O', name: 'Oxygen', mass: 15.999, category: 'nonmetal', electronegativity: 3.44, atomicRadius: 48, ionizationEnergy: 13.618, meltingPoint: -218.79, boilingPoint: -182.96, electronConfig: '[He] 2s² 2p⁴', shells: [2, 6], hybridization: ['sp², sp³'], applications: ['Respiration', 'Steel production', 'Rocket propellant', 'Water treatment', 'Medical applications'] },
    { number: 9, symbol: 'F', name: 'Fluorine', mass: 18.998, category: 'halogen', electronegativity: 3.98, atomicRadius: 42, ionizationEnergy: 17.423, meltingPoint: -219.67, boilingPoint: -188.11, electronConfig: '[He] 2s² 2p⁵', shells: [2, 7], hybridization: ['sp³'], applications: ['Toothpaste', 'Teflon coating', 'Refrigerants', 'Uranium processing', 'Pharmaceuticals'] },
    { number: 10, symbol: 'Ne', name: 'Neon', mass: 20.180, category: 'noble-gas', electronegativity: null, atomicRadius: 38, ionizationEnergy: 21.565, meltingPoint: -248.59, boilingPoint: -246.08, electronConfig: '[He] 2s² 2p⁶', shells: [2, 8], hybridization: ['None'], applications: ['Neon signs', 'Lasers', 'Cryogenic refrigeration', 'High-voltage indicators', 'Lightning arresters'] },
    { number: 11, symbol: 'Na', name: 'Sodium', mass: 22.990, category: 'alkali-metal', electronegativity: 0.93, atomicRadius: 190, ionizationEnergy: 5.139, meltingPoint: 97.72, boilingPoint: 883, electronConfig: '[Ne] 3s¹', shells: [2, 8, 1], hybridization: ['None'], applications: ['Table salt', 'Street lights', 'Soap making', 'Industrial chemicals', 'Heat transfer in nuclear reactors'] },
    { number: 12, symbol: 'Mg', name: 'Magnesium', mass: 24.305, category: 'alkaline-earth', electronegativity: 1.31, atomicRadius: 145, ionizationEnergy: 7.646, meltingPoint: 650, boilingPoint: 1090, electronConfig: '[Ne] 3s²', shells: [2, 8, 2], hybridization: ['None'], applications: ['Lightweight alloys', 'Fireworks', 'Flashes for photography', 'Removing sulfur from iron and steel', 'Medicine'] },
    { number: 13, symbol: 'Al', name: 'Aluminum', mass: 26.982, category: 'post-transition', electronegativity: 1.61, atomicRadius: 118, ionizationEnergy: 5.986, meltingPoint: 660.32, boilingPoint: 2519, electronConfig: '[Ne] 3s² 3p¹', shells: [2, 8, 3], hybridization: ['sp²', 'sp³'], applications: ['Construction', 'Packaging', 'Transportation', 'Electrical transmission lines', 'Consumer products'] },
    { number: 14, symbol: 'Si', name: 'Silicon', mass: 28.085, category: 'metalloid', electronegativity: 1.90, atomicRadius: 111, ionizationEnergy: 8.152, meltingPoint: 1414, boilingPoint: 3265, electronConfig: '[Ne] 3s² 3p²', shells: [2, 8, 4], hybridization: ['sp³'], applications: ['Semiconductors', 'Solar cells', 'Glass production', 'Ceramics', 'Silicones'] },
    { number: 15, symbol: 'P', name: 'Phosphorus', mass: 30.974, category: 'nonmetal', electronegativity: 2.19, atomicRadius: 98, ionizationEnergy: 10.487, meltingPoint: 44.15, boilingPoint: 280.5, electronConfig: '[Ne] 3s² 3p³', shells: [2, 8, 5], hybridization: ['sp³', 'sp³d'], applications: ['Fertilizers', 'Detergents', 'Food additives', 'Matches', 'Steel production'] },
    { number: 16, symbol: 'S', name: 'Sulfur', mass: 32.06, category: 'nonmetal', electronegativity: 2.58, atomicRadius: 88, ionizationEnergy: 10.360, meltingPoint: 115.21, boilingPoint: 444.72, electronConfig: '[Ne] 3s² 3p⁴', shells: [2, 8, 6], hybridization: ['sp³', 'sp³d', 'sp³d²'], applications: ['Sulfuric acid production', 'Gunpowder', 'Vulcanization of rubber', 'Fungicide', 'Fertilizers'] },
    { number: 17, symbol: 'Cl', name: 'Chlorine', mass: 35.45, category: 'halogen', electronegativity: 3.16, atomicRadius: 79, ionizationEnergy: 12.968, meltingPoint: -101.5, boilingPoint: -34.04, electronConfig: '[Ne] 3s² 3p⁵', shells: [2, 8, 7], hybridization: ['sp³', 'sp³d'], applications: ['Water purification', 'Bleaches', 'PVC production', 'Disinfectants', 'Chemical warfare'] },
    { number: 18, symbol: 'Ar', name: 'Argon', mass: 39.948, category: 'noble-gas', electronegativity: null, atomicRadius: 71, ionizationEnergy: 15.760, meltingPoint: -189.34, boilingPoint: -185.85, electronConfig: '[Ne] 3s² 3p⁶', shells: [2, 8, 8], hybridization: ['None'], applications: ['Welding', 'Light bulbs', 'Lasers', 'Growing silicon crystals', 'Insulation in windows'] },
    { number: 19, symbol: 'K', name: 'Potassium', mass: 39.098, category: 'alkali-metal', electronegativity: 0.82, atomicRadius: 243, ionizationEnergy: 4.341, meltingPoint: 63.38, boilingPoint: 759, electronConfig: '[Ar] 4s¹', shells: [2, 8, 8, 1], hybridization: ['None'], applications: ['Fertilizers', 'Soap making', 'Food products', 'Chemical reagent', 'Medicine'] },
    { number: 20, symbol: 'Ca', name: 'Calcium', mass: 40.078, category: 'alkaline-earth', electronegativity: 1.00, atomicRadius: 194, ionizationEnergy: 6.113, meltingPoint: 842, boilingPoint: 1484, electronConfig: '[Ar] 4s²', shells: [2, 8, 8, 2], hybridization: ['None'], applications: ['Construction (cement)', 'Food additive', 'Dietary supplement', 'Fertilizers', 'Water treatment'] },
    { number: 21, symbol: 'Sc', name: 'Scandium', mass: 44.956, category: 'transition-metal', electronegativity: 1.36, atomicRadius: 184, ionizationEnergy: 6.561, meltingPoint: 1541, boilingPoint: 2836, electronConfig: '[Ar] 3d¹ 4s²', shells: [2, 8, 9, 2], hybridization: ['None'], applications: ['Aluminum alloys', 'Aerospace components', 'Sports equipment', 'Stadium lighting', 'Electronics'] },
    { number: 22, symbol: 'Ti', name: 'Titanium', mass: 47.867, category: 'transition-metal', electronegativity: 1.54, atomicRadius: 176, ionizationEnergy: 6.828, meltingPoint: 1668, boilingPoint: 3287, electronConfig: '[Ar] 3d² 4s²', shells: [2, 8, 10, 2], hybridization: ['None'], applications: ['Aerospace', 'Medical implants', 'Jewelry', 'White pigment', 'Bicycles and sports equipment'] },
    { number: 23, symbol: 'V', name: 'Vanadium', mass: 50.942, category: 'transition-metal', electronegativity: 1.63, atomicRadius: 171, ionizationEnergy: 6.746, meltingPoint: 1910, boilingPoint: 3407, electronConfig: '[Ar] 3d³ 4s²', shells: [2, 8, 11, 2], hybridization: ['None'], applications: ['Steel additive', 'Aerospace', 'Nuclear applications', 'Catalysts', 'Batteries'] },
    { number: 24, symbol: 'Cr', name: 'Chromium', mass: 51.996, category: 'transition-metal', electronegativity: 1.66, atomicRadius: 166, ionizationEnergy: 6.767, meltingPoint: 1907, boilingPoint: 2671, electronConfig: '[Ar] 3d⁵ 4s¹', shells: [2, 8, 13, 1], hybridization: ['None'], applications: ['Stainless steel', 'Chrome plating', 'Dyes and pigments', 'Wood preservatives', 'Tanning leather'] },
    { number: 25, symbol: 'Mn', name: 'Manganese', mass: 54.938, category: 'transition-metal', electronegativity: 1.55, atomicRadius: 161, ionizationEnergy: 7.434, meltingPoint: 1246, boilingPoint: 2061, electronConfig: '[Ar] 3d⁵ 4s²', shells: [2, 8, 13, 2], hybridization: ['None'], applications: ['Steel production', 'Batteries', 'Aluminum alloys', 'Fertilizers', 'Pigments'] },
    { number: 26, symbol: 'Fe', name: 'Iron', mass: 55.845, category: 'transition-metal', electronegativity: 1.83, atomicRadius: 156, ionizationEnergy: 7.902, meltingPoint: 1538, boilingPoint: 2861, electronConfig: '[Ar] 3d⁶ 4s²', shells: [2, 8, 14, 2], hybridization: ['None'], applications: ['Steel and alloys', 'Construction', 'Tools', 'Automotive industry', 'Hemoglobin in blood'] },
    { number: 27, symbol: 'Co', name: 'Cobalt', mass: 58.933, category: 'transition-metal', electronegativity: 1.88, atomicRadius: 152, ionizationEnergy: 7.881, meltingPoint: 1495, boilingPoint: 2927, electronConfig: '[Ar] 3d⁷ 4s²', shells: [2, 8, 15, 2], hybridization: ['None'], applications: ['Alloys', 'Lithium-ion batteries', 'Magnets', 'Catalysts', 'Pigments'] },
    { number: 28, symbol: 'Ni', name: 'Nickel', mass: 58.693, category: 'transition-metal', electronegativity: 1.91, atomicRadius: 149, ionizationEnergy: 7.640, meltingPoint: 1455, boilingPoint: 2913, electronConfig: '[Ar] 3d⁸ 4s²', shells: [2, 8, 16, 2], hybridization: ['None'], applications: ['Stainless steel', 'Batteries', 'Coins', 'Electronics', 'Plating'] },
    { number: 29, symbol: 'Cu', name: 'Copper', mass: 63.546, category: 'transition-metal', electronegativity: 1.90, atomicRadius: 145, ionizationEnergy: 7.726, meltingPoint: 1084.62, boilingPoint: 2562, electronConfig: '[Ar] 3d¹⁰ 4s¹', shells: [2, 8, 18, 1], hybridization: ['None'], applications: ['Electrical wiring', 'Plumbing', 'Electronics', 'Coins', 'Antimicrobial surfaces'] },
    { number: 30, symbol: 'Zn', name: 'Zinc', mass: 65.38, category: 'transition-metal', electronegativity: 1.65, atomicRadius: 142, ionizationEnergy: 9.394, meltingPoint: 419.53, boilingPoint: 907, electronConfig: '[Ar] 3d¹⁰ 4s²', shells: [2, 8, 18, 2], hybridization: ['None'], applications: ['Galvanization', 'Brass and bronze', 'Batteries', 'Die casting', 'Dietary supplement'] },
    { number: 31, symbol: 'Ga', name: 'Gallium', mass: 69.723, category: 'post-transition', electronegativity: 1.81, atomicRadius: 136, ionizationEnergy: 5.999, meltingPoint: 29.76, boilingPoint: 2204, electronConfig: '[Ar] 3d¹⁰ 4s² 4p¹', shells: [2, 8, 18, 3], hybridization: ['sp²', 'sp³'], applications: ['Semiconductors', 'LEDs', 'Solar panels', 'Thermometers', 'Medical imaging'] },
    { number: 32, symbol: 'Ge', name: 'Germanium', mass: 72.630, category: 'metalloid', electronegativity: 2.01, atomicRadius: 125, ionizationEnergy: 7.900, meltingPoint: 938.25, boilingPoint: 2833, electronConfig: '[Ar] 3d¹⁰ 4s² 4p²', shells: [2, 8, 18, 4], hybridization: ['sp³'], applications: ['Fiber optics', 'Infrared optics', 'Semiconductors', 'Solar cells', 'Polymerization catalysts'] },
    { number: 33, symbol: 'As', name: 'Arsenic', mass: 74.922, category: 'metalloid', electronegativity: 2.18, atomicRadius: 114, ionizationEnergy: 9.815, meltingPoint: 816.9, boilingPoint: 613, electronConfig: '[Ar] 3d¹⁰ 4s² 4p³', shells: [2, 8, 18, 5], hybridization: ['sp³'], applications: ['Semiconductors', 'Wood preservatives', 'Lead alloys', 'Medicine', 'Pesticides'] },
    { number: 34, symbol: 'Se', name: 'Selenium', mass: 78.971, category: 'nonmetal', electronegativity: 2.55, atomicRadius: 103, ionizationEnergy: 9.752, meltingPoint: 221, boilingPoint: 685, electronConfig: '[Ar] 3d¹⁰ 4s² 4p⁴', shells: [2, 8, 18, 6], hybridization: ['sp³'], applications: ['Glass production', 'Photocopying', 'Solar cells', 'Antidandruff shampoos', 'Dietary supplement'] },
    { number: 35, symbol: 'Br', name: 'Bromine', mass: 79.904, category: 'halogen', electronegativity: 2.96, atomicRadius: 94, ionizationEnergy: 11.814, meltingPoint: -7.2, boilingPoint: 58.8, electronConfig: '[Ar] 3d¹⁰ 4s² 4p⁵', shells: [2, 8, 18, 7], hybridization: ['sp³'], applications: ['Flame retardants', 'Photography', 'Pesticides', 'Medicines', 'Dyes'] },
    { number: 36, symbol: 'Kr', name: 'Krypton', mass: 83.798, category: 'noble-gas', electronegativity: 3.00, atomicRadius: 88, ionizationEnergy: 14.000, meltingPoint: -157.36, boilingPoint: -153.22, electronConfig: '[Ar] 3d¹⁰ 4s² 4p⁶', shells: [2, 8, 18, 8], hybridization: ['None'], applications: ['Lighting', 'Laser research', 'High-speed photography', 'Insulation for windows', 'Detecting radioactive leaks'] },
    { number: 37, symbol: 'Rb', name: 'Rubidium', mass: 85.468, category: 'alkali-metal', electronegativity: 0.82, atomicRadius: 265, ionizationEnergy: 4.177, meltingPoint: 39.31, boilingPoint: 688, electronConfig: '[Kr] 5s¹', shells: [2, 8, 18, 8, 1], hybridization: ['None'], applications: ['Vacuum tubes', 'Photoelectric cells', 'Atomic clocks', 'Fireworks', 'Medical imaging'] },
    { number: 38, symbol: 'Sr', name: 'Strontium', mass: 87.62, category: 'alkaline-earth', electronegativity: 0.95, atomicRadius: 219, ionizationEnergy: 5.695, meltingPoint: 777, boilingPoint: 1377, electronConfig: '[Kr] 5s²', shells: [2, 8, 18, 8, 2], hybridization: ['None'], applications: ['Fireworks', 'Ceramics', 'Glass manufacturing', 'Luminous paint', 'Toothpaste for sensitive teeth'] },
    { number: 39, symbol: 'Y', name: 'Yttrium', mass: 88.906, category: 'transition-metal', electronegativity: 1.22, atomicRadius: 212, ionizationEnergy: 6.217, meltingPoint: 1526, boilingPoint: 3336, electronConfig: '[Kr] 4d¹ 5s²', shells: [2, 8, 18, 9, 2], hybridization: ['None'], applications: ['LEDs and phosphors', 'Laser technology', 'Cancer treatment', 'Superconductors', 'Ceramic materials'] },
    { number: 40, symbol: 'Zr', name: 'Zirconium', mass: 91.224, category: 'transition-metal', electronegativity: 1.33, atomicRadius: 206, ionizationEnergy: 6.634, meltingPoint: 1855, boilingPoint: 4409, electronConfig: '[Kr] 4d² 5s²', shells: [2, 8, 18, 10, 2], hybridization: ['None'], applications: ['Nuclear reactors', 'Chemical processing equipment', 'Ceramics', 'Catalytic converters', 'Surgical implants'] },
    { number: 41, symbol: 'Nb', name: 'Niobium', mass: 92.906, category: 'transition-metal', electronegativity: 1.6, atomicRadius: 198, ionizationEnergy: 6.759, meltingPoint: 2477, boilingPoint: 4744, electronConfig: '[Kr] 4d⁴ 5s¹', shells: [2, 8, 18, 12, 1], hybridization: ['None'], applications: ['Steel alloys', 'Superconductors', 'Jewelry', 'Nuclear industry', 'Electronics'] },
    { number: 42, symbol: 'Mo', name: 'Molybdenum', mass: 95.95, category: 'transition-metal', electronegativity: 2.16, atomicRadius: 190, ionizationEnergy: 7.092, meltingPoint: 2623, boilingPoint: 4639, electronConfig: '[Kr] 4d⁵ 5s¹', shells: [2, 8, 18, 13, 1], hybridization: ['None'], applications: ['High-strength steel alloys', 'Catalysts', 'Lubricants', 'Nuclear energy applications', 'Electronics'] },
    { number: 43, symbol: 'Tc', name: 'Technetium', mass: 98, category: 'transition-metal', electronegativity: 1.9, atomicRadius: 183, ionizationEnergy: 7.28, meltingPoint: 2157, boilingPoint: 4265, electronConfig: '[Kr] 4d⁵ 5s²', shells: [2, 8, 18, 13, 2], hybridization: ['None'], applications: ['Medical imaging', 'Nuclear medicine', 'Radioactive tracer', 'Research', 'Nuclear batteries'] },
    { number: 44, symbol: 'Ru', name: 'Ruthenium', mass: 101.07, category: 'transition-metal', electronegativity: 2.2, atomicRadius: 178, ionizationEnergy: 7.361, meltingPoint: 2334, boilingPoint: 4150, electronConfig: '[Kr] 4d⁷ 5s¹', shells: [2, 8, 18, 15, 1], hybridization: ['None'], applications: ['Wear-resistant electrical contacts', 'Catalysts', 'Jewelry', 'Electronics', 'Solar energy conversion'] },
    { number: 45, symbol: 'Rh', name: 'Rhodium', mass: 102.91, category: 'transition-metal', electronegativity: 2.28, atomicRadius: 173, ionizationEnergy: 7.459, meltingPoint: 1964, boilingPoint: 3695, electronConfig: '[Kr] 4d⁸ 5s¹', shells: [2, 8, 18, 16, 1], hybridization: ['None'], applications: ['Catalytic converters', 'Jewelry', 'Mirrors and reflectors', 'Electrical contacts', 'Temperature measurement'] },
    { number: 46, symbol: 'Pd', name: 'Palladium', mass: 106.42, category: 'transition-metal', electronegativity: 2.2, atomicRadius: 169, ionizationEnergy: 8.337, meltingPoint: 1555, boilingPoint: 2963, electronConfig: '[Kr] 4d¹⁰', shells: [2, 8, 18, 18], hybridization: ['None'], applications: ['Catalytic converters', 'Electronics', 'Dental fillings', 'Jewelry', 'Hydrogen storage'] },
    { number: 47, symbol: 'Ag', name: 'Silver', mass: 107.87, category: 'transition-metal', electronegativity: 1.93, atomicRadius: 165, ionizationEnergy: 7.576, meltingPoint: 961.78, boilingPoint: 2162, electronConfig: '[Kr] 4d¹⁰ 5s¹', shells: [2, 8, 18, 18, 1], hybridization: ['None'], applications: ['Jewelry', 'Photography', 'Electrical conductors', 'Mirrors', 'Antimicrobial agent'] },
    { number: 48, symbol: 'Cd', name: 'Cadmium', mass: 112.41, category: 'transition-metal', electronegativity: 1.69, atomicRadius: 161, ionizationEnergy: 8.994, meltingPoint: 321.07, boilingPoint: 767, electronConfig: '[Kr] 4d¹⁰ 5s²', shells: [2, 8, 18, 18, 2], hybridization: ['None'], applications: ['Batteries', 'Pigments', 'Coatings', 'Stabilizers for plastics', 'Nuclear fission control'] },
    { number: 49, symbol: 'In', name: 'Indium', mass: 114.82, category: 'post-transition', electronegativity: 1.78, atomicRadius: 156, ionizationEnergy: 5.786, meltingPoint: 156.6, boilingPoint: 2072, electronConfig: '[Kr] 4d¹⁰ 5s² 5p¹', shells: [2, 8, 18, 18, 3], hybridization: ['sp²', 'sp³'], applications: ['Touch screens', 'Solar cells', 'Semiconductors', 'Solders', 'LCD displays'] },
    { number: 50, symbol: 'Sn', name: 'Tin', mass: 118.71, category: 'post-transition', electronegativity: 1.96, atomicRadius: 145, ionizationEnergy: 7.344, meltingPoint: 231.93, boilingPoint: 2602, electronConfig: '[Kr] 4d¹⁰ 5s² 5p²', shells: [2, 8, 18, 18, 4], hybridization: ['sp³'], applications: ['Solder', 'Food packaging', 'Superconductors', 'Pewter', 'Bronze and brass alloys'] },
    { number: 51, symbol: 'Sb', name: 'Antimony', mass: 121.76, category: 'metalloid', electronegativity: 2.05, atomicRadius: 133, ionizationEnergy: 8.64, meltingPoint: 630.63, boilingPoint: 1587, electronConfig: '[Kr] 4d¹⁰ 5s² 5p³', shells: [2, 8, 18, 18, 5], hybridization: ['sp³'], applications: ['Flame retardants', 'Batteries', 'Semiconductors', 'Alloys', 'Ceramics'] },
    { number: 52, symbol: 'Te', name: 'Tellurium', mass: 127.60, category: 'metalloid', electronegativity: 2.1, atomicRadius: 123, ionizationEnergy: 9.010, meltingPoint: 449.51, boilingPoint: 988, electronConfig: '[Kr] 4d¹⁰ 5s² 5p⁴', shells: [2, 8, 18, 18, 6], hybridization: ['sp³'], applications: ['Solar panels', 'Semiconductors', 'Glass tinting', 'Thermoelectric devices', 'Alloys'] },
    { number: 53, symbol: 'I', name: 'Iodine', mass: 126.90, category: 'halogen', electronegativity: 2.66, atomicRadius: 115, ionizationEnergy: 10.451, meltingPoint: 113.7, boilingPoint: 184.3, electronConfig: '[Kr] 4d¹⁰ 5s² 5p⁵', shells: [2, 8, 18, 18, 7], hybridization: ['sp³'], applications: ['Antiseptics', 'Photography', 'Dyes', 'Medicine', 'Nutrition'] },
    { number: 54, symbol: 'Xe', name: 'Xenon', mass: 131.29, category: 'noble-gas', electronegativity: 2.60, atomicRadius: 108, ionizationEnergy: 12.130, meltingPoint: -111.75, boilingPoint: -108.12, electronConfig: '[Kr] 4d¹⁰ 5s² 5p⁶', shells: [2, 8, 18, 18, 8], hybridization: ['None'], applications: ['Lighting', 'Medical imaging', 'Anesthesia', 'Ion propulsion systems', 'Insulation'] },
    { number: 55, symbol: 'Cs', name: 'Cesium', mass: 132.91, category: 'alkali-metal', electronegativity: 0.79, atomicRadius: 298, ionizationEnergy: 3.894, meltingPoint: 28.44, boilingPoint: 671, electronConfig: '[Xe] 6s¹', shells: [2, 8, 18, 18, 8, 1], hybridization: ['None'], applications: ['Atomic clocks', 'Photoelectric cells', 'Catalysts', 'Deep oil drilling', 'Medical applications'] },
    { number: 56, symbol: 'Ba', name: 'Barium', mass: 137.33, category: 'alkaline-earth', electronegativity: 0.89, atomicRadius: 253, ionizationEnergy: 5.212, meltingPoint: 727, boilingPoint: 1870, electronConfig: '[Xe] 6s²', shells: [2, 8, 18, 18, 8, 2], hybridization: ['None'], applications: ['Oil and gas industry', 'X-ray imaging', 'Fireworks (green color)', 'Glass manufacturing', 'Spark plugs'] },
    
    // Lanthanides (57-71)
    { number: 57, symbol: 'La', name: 'Lanthanum', mass: 138.91, category: 'lanthanide', electronegativity: 1.1, atomicRadius: 195, ionizationEnergy: 5.577, meltingPoint: 920, boilingPoint: 3464, electronConfig: '[Xe] 5d¹ 6s²', shells: [2, 8, 18, 18, 9, 2], hybridization: ['None'], applications: ['Hydrogen storage', 'Carbon arc lamps', 'Optical glasses', 'Catalysts', 'Battery electrodes'] },
    { number: 58, symbol: 'Ce', name: 'Cerium', mass: 140.12, category: 'lanthanide', electronegativity: 1.12, atomicRadius: 185, ionizationEnergy: 5.539, meltingPoint: 798, boilingPoint: 3360, electronConfig: '[Xe] 4f¹ 5d¹ 6s²', shells: [2, 8, 18, 19, 9, 2], hybridization: ['None'], applications: ['Catalytic converters', 'Glass polishing', 'Self-cleaning ovens', 'Carbon arc lighting', 'Alloys'] },
    { number: 59, symbol: 'Pr', name: 'Praseodymium', mass: 140.91, category: 'lanthanide', electronegativity: 1.13, atomicRadius: 185, ionizationEnergy: 5.473, meltingPoint: 931, boilingPoint: 3290, electronConfig: '[Xe] 4f³ 6s²', shells: [2, 8, 18, 21, 8, 2], hybridization: ['None'], applications: ['Magnets', 'Specialized glasses', 'Carbon arc lighting', 'Coloring ceramics', 'Catalysts'] },
    { number: 60, symbol: 'Nd', name: 'Neodymium', mass: 144.24, category: 'lanthanide', electronegativity: 1.14, atomicRadius: 185, ionizationEnergy: 5.525, meltingPoint: 1016, boilingPoint: 3100, electronConfig: '[Xe] 4f⁴ 6s²', shells: [2, 8, 18, 22, 8, 2], hybridization: ['None'], applications: ['Strong permanent magnets', 'Lasers', 'Glass coloring', 'Computer hard disks', 'Microphones and speakers'] },
    { number: 61, symbol: 'Pm', name: 'Promethium', mass: 145, category: 'lanthanide', electronegativity: 1.13, atomicRadius: 185, ionizationEnergy: 5.582, meltingPoint: 1042, boilingPoint: 3000, electronConfig: '[Xe] 4f⁵ 6s²', shells: [2, 8, 18, 23, 8, 2], hybridization: ['None'], applications: ['Nuclear batteries', 'Thickness measurement', 'Portable X-ray devices', 'Luminous paint', 'Research'] },
    { number: 62, symbol: 'Sm', name: 'Samarium', mass: 150.36, category: 'lanthanide', electronegativity: 1.17, atomicRadius: 185, ionizationEnergy: 5.644, meltingPoint: 1072, boilingPoint: 1794, electronConfig: '[Xe] 4f⁶ 6s²', shells: [2, 8, 18, 24, 8, 2], hybridization: ['None'], applications: ['Permanent magnets', 'Cancer treatment', 'Nuclear reactors', 'Carbon arc lighting', 'Infrared absorption glass'] },
    { number: 63, symbol: 'Eu', name: 'Europium', mass: 151.96, category: 'lanthanide', electronegativity: 1.2, atomicRadius: 185, ionizationEnergy: 5.670, meltingPoint: 822, boilingPoint: 1596, electronConfig: '[Xe] 4f⁷ 6s²', shells: [2, 8, 18, 25, 8, 2], hybridization: ['None'], applications: ['Red color in TV screens', 'Anti-counterfeiting in Euro banknotes', 'LED lighting', 'Lasers', 'Nuclear reactor control rods'] },
    { number: 64, symbol: 'Gd', name: 'Gadolinium', mass: 157.25, category: 'lanthanide', electronegativity: 1.2, atomicRadius: 180, ionizationEnergy: 6.150, meltingPoint: 1313, boilingPoint: 3273, electronConfig: '[Xe] 4f⁷ 5d¹ 6s²', shells: [2, 8, 18, 25, 9, 2], hybridization: ['None'], applications: ['MRI contrast agents', 'Nuclear reactors', 'Compact discs', 'Microwave applications', 'Temperature sensors'] },
    { number: 65, symbol: 'Tb', name: 'Terbium', mass: 158.93, category: 'lanthanide', electronegativity: 1.2, atomicRadius: 175, ionizationEnergy: 5.864, meltingPoint: 1356, boilingPoint: 3230, electronConfig: '[Xe] 4f⁹ 6s²', shells: [2, 8, 18, 27, 8, 2], hybridization: ['None'], applications: ['Green phosphors in displays', 'Solid state devices', 'Fuel cells', 'Naval sonar systems', 'Electronic devices'] },
    { number: 66, symbol: 'Dy', name: 'Dysprosium', mass: 162.50, category: 'lanthanide', electronegativity: 1.22, atomicRadius: 175, ionizationEnergy: 5.939, meltingPoint: 1412, boilingPoint: 2567, electronConfig: '[Xe] 4f¹⁰ 6s²', shells: [2, 8, 18, 28, 8, 2], hybridization: ['None'], applications: ['Hard disk drives', 'Lasers', 'Nuclear reactors', 'Commercial lighting', 'High-intensity lighting'] },
    { number: 67, symbol: 'Ho', name: 'Holmium', mass: 164.93, category: 'lanthanide', electronegativity: 1.23, atomicRadius: 175, ionizationEnergy: 6.022, meltingPoint: 1474, boilingPoint: 2700, electronConfig: '[Xe] 4f¹¹ 6s²', shells: [2, 8, 18, 29, 8, 2], hybridization: ['None'], applications: ['Strongest magnets', 'Nuclear reactors', 'Lasers', 'Glass coloring', 'Microwave equipment'] },
    { number: 68, symbol: 'Er', name: 'Erbium', mass: 167.26, category: 'lanthanide', electronegativity: 1.24, atomicRadius: 175, ionizationEnergy: 6.108, meltingPoint: 1529, boilingPoint: 2868, electronConfig: '[Xe] 4f¹² 6s²', shells: [2, 8, 18, 30, 8, 2], hybridization: ['None'], applications: ['Fiber optic communications', 'Lasers for medical use', 'Metallurgy', 'Nuclear technology', 'Glass colorant'] },
    { number: 69, symbol: 'Tm', name: 'Thulium', mass: 168.93, category: 'lanthanide', electronegativity: 1.25, atomicRadius: 175, ionizationEnergy: 6.184, meltingPoint: 1545, boilingPoint: 1950, electronConfig: '[Xe] 4f¹³ 6s²', shells: [2, 8, 18, 31, 8, 2], hybridization: ['None'], applications: ['Portable X-ray devices', 'Lasers', 'Ceramic magnetic materials', 'Metal halide lamps', 'Radiation source for cancer treatment'] },
    { number: 70, symbol: 'Yb', name: 'Ytterbium', mass: 173.05, category: 'lanthanide', electronegativity: 1.1, atomicRadius: 175, ionizationEnergy: 6.254, meltingPoint: 819, boilingPoint: 1196, electronConfig: '[Xe] 4f¹⁴ 6s²', shells: [2, 8, 18, 32, 8, 2], hybridization: ['None'], applications: ['Stress gauges', 'Laser materials', 'Improving stainless steel properties', 'Portable X-ray machines', 'Memory devices'] },
    { number: 71, symbol: 'Lu', name: 'Lutetium', mass: 174.97, category: 'lanthanide', electronegativity: 1.27, atomicRadius: 175, ionizationEnergy: 5.426, meltingPoint: 1663, boilingPoint: 3402, electronConfig: '[Xe] 4f¹⁴ 5d¹ 6s²', shells: [2, 8, 18, 32, 9, 2], hybridization: ['None'], applications: ['PET scan detectors', 'High refractive index glass', 'Catalysts for petroleum cracking', 'Dating meteorites', 'Phosphors'] },
    
    // Post-Lanthanides (72-86)
    { number: 72, symbol: 'Hf', name: 'Hafnium', mass: 178.49, category: 'transition-metal', electronegativity: 1.3, atomicRadius: 167, ionizationEnergy: 6.825, meltingPoint: 2233, boilingPoint: 4603, electronConfig: '[Xe] 4f¹⁴ 5d² 6s²', shells: [2, 8, 18, 32, 10, 2], hybridization: ['None'], applications: ['Nuclear reactor control rods', 'Superalloys', 'Plasma cutting tips', 'Microprocessors', 'High-temperature ceramics'] },
    { number: 73, symbol: 'Ta', name: 'Tantalum', mass: 180.95, category: 'transition-metal', electronegativity: 1.5, atomicRadius: 149, ionizationEnergy: 7.89, meltingPoint: 3017, boilingPoint: 5458, electronConfig: '[Xe] 4f¹⁴ 5d³ 6s²', shells: [2, 8, 18, 32, 11, 2], hybridization: ['None'], applications: ['Electronic components', 'Surgical implants', 'Chemical equipment', 'Jet engine components', 'Capacitors'] },
    { number: 74, symbol: 'W', name: 'Tungsten', mass: 183.84, category: 'transition-metal', electronegativity: 2.36, atomicRadius: 141, ionizationEnergy: 7.98, meltingPoint: 3422, boilingPoint: 5555, electronConfig: '[Xe] 4f¹⁴ 5d⁴ 6s²', shells: [2, 8, 18, 32, 12, 2], hybridization: ['None'], applications: ['Light bulb filaments', 'X-ray tubes', 'Heating elements', 'Armor-piercing ammunition', 'Welding electrodes'] },
    { number: 75, symbol: 'Re', name: 'Rhenium', mass: 186.21, category: 'transition-metal', electronegativity: 1.9, atomicRadius: 137, ionizationEnergy: 7.88, meltingPoint: 3186, boilingPoint: 5596, electronConfig: '[Xe] 4f¹⁴ 5d⁵ 6s²', shells: [2, 8, 18, 32, 13, 2], hybridization: ['None'], applications: ['Superalloys for jet engines', 'Catalysts', 'Filaments', 'Thermocouples', 'Electrical contacts'] },
    { number: 76, symbol: 'Os', name: 'Osmium', mass: 190.23, category: 'transition-metal', electronegativity: 2.2, atomicRadius: 135, ionizationEnergy: 8.7, meltingPoint: 3033, boilingPoint: 5012, electronConfig: '[Xe] 4f¹⁴ 5d⁶ 6s²', shells: [2, 8, 18, 32, 14, 2], hybridization: ['None'], applications: ['Pen tips', 'Instrument pivots', 'Electrical contacts', 'Fingerprint detection', 'Staining biological samples'] },
    { number: 77, symbol: 'Ir', name: 'Iridium', mass: 192.22, category: 'transition-metal', electronegativity: 2.2, atomicRadius: 136, ionizationEnergy: 9.1, meltingPoint: 2446, boilingPoint: 4428, electronConfig: '[Xe] 4f¹⁴ 5d⁷ 6s²', shells: [2, 8, 18, 32, 15, 2], hybridization: ['None'], applications: ['Spark plugs', 'Crucibles', 'Aerospace components', 'Compass bearings', 'Medical radiotherapy'] },
    { number: 78, symbol: 'Pt', name: 'Platinum', mass: 195.08, category: 'transition-metal', electronegativity: 2.28, atomicRadius: 139, ionizationEnergy: 9.0, meltingPoint: 1768.3, boilingPoint: 3825, electronConfig: '[Xe] 4f¹⁴ 5d⁹ 6s¹', shells: [2, 8, 18, 32, 17, 1], hybridization: ['None'], applications: ['Catalytic converters', 'Jewelry', 'Laboratory equipment', 'Dental fillings', 'Cancer drugs'] },
    { number: 79, symbol: 'Au', name: 'Gold', mass: 196.97, category: 'transition-metal', electronegativity: 2.54, atomicRadius: 144, ionizationEnergy: 9.226, meltingPoint: 1064.18, boilingPoint: 2856, electronConfig: '[Xe] 4f¹⁴ 5d¹⁰ 6s¹', shells: [2, 8, 18, 32, 18, 1], hybridization: ['None'], applications: ['Jewelry', 'Electronics', 'Dentistry', 'Medicine', 'Monetary exchange'] },
    { number: 80, symbol: 'Hg', name: 'Mercury', mass: 200.59, category: 'transition-metal', electronegativity: 2.0, atomicRadius: 151, ionizationEnergy: 10.438, meltingPoint: -38.83, boilingPoint: 356.73, electronConfig: '[Xe] 4f¹⁴ 5d¹⁰ 6s²', shells: [2, 8, 18, 32, 18, 2], hybridization: ['None'], applications: ['Thermometers', 'Fluorescent lamps', 'Dental amalgams', 'Batteries', 'Switches'] },
    { number: 81, symbol: 'Tl', name: 'Thallium', mass: 204.38, category: 'post-transition', electronegativity: 1.62, atomicRadius: 170, ionizationEnergy: 6.108, meltingPoint: 304, boilingPoint: 1473, electronConfig: '[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p¹', shells: [2, 8, 18, 32, 18, 3], hybridization: ['None'], applications: ['Electronics', 'High-temperature superconductors', 'Infrared detectors', 'Medical imaging', 'Glass manufacturing'] },
    { number: 82, symbol: 'Pb', name: 'Lead', mass: 207.2, category: 'post-transition', electronegativity: 2.33, atomicRadius: 175, ionizationEnergy: 7.417, meltingPoint: 327.46, boilingPoint: 1749, electronConfig: '[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p²', shells: [2, 8, 18, 32, 18, 4], hybridization: ['sp³'], applications: ['Batteries', 'Radiation shields', 'Solder', 'Ammunition', 'Construction materials'] },
    { number: 83, symbol: 'Bi', name: 'Bismuth', mass: 208.98, category: 'post-transition', electronegativity: 2.02, atomicRadius: 156, ionizationEnergy: 7.289, meltingPoint: 271.5, boilingPoint: 1564, electronConfig: '[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p³', shells: [2, 8, 18, 32, 18, 5], hybridization: ['None'], applications: ['Pharmaceuticals', 'Cosmetics', 'Food processing', 'Solders', 'Fire detection systems'] },
    { number: 84, symbol: 'Po', name: 'Polonium', mass: 209, category: 'post-transition', electronegativity: 2.0, atomicRadius: 168, ionizationEnergy: 8.417, meltingPoint: 254, boilingPoint: 962, electronConfig: '[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p⁴', shells: [2, 8, 18, 32, 18, 6], hybridization: ['None'], applications: ['Antistatic devices', 'Thermoelectric power in space vehicles', 'Neutron sources', 'Research', 'Heat sources in space satellites'] },
    { number: 85, symbol: 'At', name: 'Astatine', mass: 210, category: 'halogen', electronegativity: 2.2, atomicRadius: 140, ionizationEnergy: 9.5, meltingPoint: 302, boilingPoint: 337, electronConfig: '[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p⁵', shells: [2, 8, 18, 32, 18, 7], hybridization: ['None'], applications: ['Cancer research', 'Medical radiotherapy', 'Research', 'Radiopharmaceuticals', 'Research in nuclear physics'] },
    { number: 86, symbol: 'Rn', name: 'Radon', mass: 222, category: 'noble-gas', electronegativity: null, atomicRadius: 150, ionizationEnergy: 10.748, meltingPoint: -71, boilingPoint: -61.7, electronConfig: '[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p⁶', shells: [2, 8, 18, 32, 18, 8], hybridization: ['None'], applications: ['Cancer treatment', 'Radon gas testing', 'Research', 'Geophysical research', 'Earthquake prediction'] },
    
    // Actinides (89-103)
    { number: 87, symbol: 'Fr', name: 'Francium', mass: 223, category: 'alkali-metal', electronegativity: 0.7, atomicRadius: 260, ionizationEnergy: 4.073, meltingPoint: 27, boilingPoint: 677, electronConfig: '[Rn] 7s¹', shells: [2, 8, 18, 32, 18, 8, 1], hybridization: ['None'], applications: ['Research', 'Cancer treatment research', 'Atomic structure studies', 'Physics research', 'Educational purposes'] },
    { number: 88, symbol: 'Ra', name: 'Radium', mass: 226, category: 'alkaline-earth', electronegativity: 0.9, atomicRadius: 223, ionizationEnergy: 5.279, meltingPoint: 700, boilingPoint: 1737, electronConfig: '[Rn] 7s²', shells: [2, 8, 18, 32, 18, 8, 2], hybridization: ['None'], applications: ['Cancer treatment', 'Luminous paints', 'Radiography', 'Lightning rods', 'Research in radiochemistry'] },
    { number: 89, symbol: 'Ac', name: 'Actinium', mass: 227, category: 'actinide', electronegativity: 1.1, atomicRadius: 195, ionizationEnergy: 5.17, meltingPoint: 1050, boilingPoint: 3200, electronConfig: '[Rn] 6d¹ 7s²', shells: [2, 8, 18, 32, 18, 9, 2], hybridization: ['None'], applications: ['Neutron sources', 'Cancer therapy', 'Thermoelectric power sources', 'Research', 'Radiation therapy'] },
    { number: 90, symbol: 'Th', name: 'Thorium', mass: 232.04, category: 'actinide', electronegativity: 1.3, atomicRadius: 180, ionizationEnergy: 6.08, meltingPoint: 1750, boilingPoint: 4820, electronConfig: '[Rn] 6d² 7s²', shells: [2, 8, 18, 32, 18, 10, 2], hybridization: ['None'], applications: ['Nuclear fuel', 'High-temperature ceramics', 'Gas mantles', 'Aerospace components', 'Optical lenses'] },
    { number: 91, symbol: 'Pa', name: 'Protactinium', mass: 231.04, category: 'actinide', electronegativity: 1.5, atomicRadius: 180, ionizationEnergy: 5.89, meltingPoint: 1572, boilingPoint: 4000, electronConfig: '[Rn] 5f² 6d¹ 7s²', shells: [2, 8, 18, 32, 20, 9, 2], hybridization: ['None'], applications: ['Research', 'Nuclear physics', 'Dating geological samples', 'Radiochemistry studies', 'Scientific instruments'] },
    { number: 92, symbol: 'U', name: 'Uranium', mass: 238.03, category: 'actinide', electronegativity: 1.38, atomicRadius: 175, ionizationEnergy: 6.194, meltingPoint: 1135, boilingPoint: 4131, electronConfig: '[Rn] 5f³ 6d¹ 7s²', shells: [2, 8, 18, 32, 21, 9, 2], hybridization: ['None'], applications: ['Nuclear fuel', 'Nuclear weapons', 'Counterweights', 'Radiation shielding', 'Dating geological formations'] },
    { number: 93, symbol: 'Np', name: 'Neptunium', mass: 237, category: 'actinide', electronegativity: 1.36, atomicRadius: 175, ionizationEnergy: 6.266, meltingPoint: 644, boilingPoint: 4000, electronConfig: '[Rn] 5f⁴ 6d¹ 7s²', shells: [2, 8, 18, 32, 22, 9, 2], hybridization: ['None'], applications: ['Nuclear reactors', 'Neutron detection', 'Space power systems', 'Research', 'Nuclear weapons'] },
    { number: 94, symbol: 'Pu', name: 'Plutonium', mass: 244, category: 'actinide', electronegativity: 1.28, atomicRadius: 175, ionizationEnergy: 6.026, meltingPoint: 640, boilingPoint: 3228, electronConfig: '[Rn] 5f⁶ 7s²', shells: [2, 8, 18, 32, 24, 8, 2], hybridization: ['None'], applications: ['Nuclear weapons', 'Nuclear reactors', 'Spacecraft power', 'Heart pacemakers', 'Research'] },
    { number: 95, symbol: 'Am', name: 'Americium', mass: 243, category: 'actinide', electronegativity: 1.3, atomicRadius: 175, ionizationEnergy: 5.974, meltingPoint: 1176, boilingPoint: 2011, electronConfig: '[Rn] 5f⁷ 7s²', shells: [2, 8, 18, 32, 25, 8, 2], hybridization: ['None'], applications: ['Smoke detectors', 'Thickness gauges', 'Industrial density gauges', 'Medical diagnostics', 'Research'] },
    { number: 96, symbol: 'Cm', name: 'Curium', mass: 247, category: 'actinide', electronegativity: 1.3, atomicRadius: 176, ionizationEnergy: 5.991, meltingPoint: 1345, boilingPoint: 3110, electronConfig: '[Rn] 5f⁷ 6d¹ 7s²', shells: [2, 8, 18, 32, 25, 9, 2], hybridization: ['None'], applications: ['Scientific research', 'Radioisotope thermoelectric generators', 'Alpha particles source', 'Radiotherapy', 'Neutron sources'] },
    { number: 97, symbol: 'Bk', name: 'Berkelium', mass: 247, category: 'actinide', electronegativity: 1.3, atomicRadius: 176, ionizationEnergy: 6.198, meltingPoint: 1050, boilingPoint: 2900, electronConfig: '[Rn] 5f⁹ 7s²', shells: [2, 8, 18, 32, 27, 8, 2], hybridization: ['None'], applications: ['Research', 'Creating heavier elements', 'Nuclear science', 'Medical research', 'Nuclear medicine'] },
    { number: 98, symbol: 'Cf', name: 'Californium', mass: 251, category: 'actinide', electronegativity: 1.3, atomicRadius: 186, ionizationEnergy: 6.282, meltingPoint: 900, boilingPoint: 1470, electronConfig: '[Rn] 5f¹⁰ 7s²', shells: [2, 8, 18, 32, 28, 8, 2], hybridization: ['None'], applications: ['Neutron source', 'Cancer treatment', 'Nuclear reactors startup', 'Metal detection', 'Oil well logging'] },
    { number: 99, symbol: 'Es', name: 'Einsteinium', mass: 252, category: 'actinide', electronegativity: 1.3, atomicRadius: 186, ionizationEnergy: 6.42, meltingPoint: 860, boilingPoint: 996, electronConfig: '[Rn] 5f¹¹ 7s²', shells: [2, 8, 18, 32, 29, 8, 2], hybridization: ['None'], applications: ['Research', 'Nuclear studies', 'Creating heavier elements', 'Scientific studies', 'Academic research'] },
    { number: 100, symbol: 'Fm', name: 'Fermium', mass: 257, category: 'actinide', electronegativity: 1.3, atomicRadius: 186, ionizationEnergy: 6.5, meltingPoint: 1527, boilingPoint: null, electronConfig: '[Rn] 5f¹² 7s²', shells: [2, 8, 18, 32, 30, 8, 2], hybridization: ['None'], applications: ['Research', 'Creating heavier elements', 'Studying chemical properties of actinides', 'Scientific investigation', 'Academic research'] },
    { number: 101, symbol: 'Md', name: 'Mendelevium', mass: 258, category: 'actinide', electronegativity: 1.3, atomicRadius: 186, ionizationEnergy: 6.58, meltingPoint: 827, boilingPoint: null, electronConfig: '[Rn] 5f¹³ 7s²', shells: [2, 8, 18, 32, 31, 8, 2], hybridization: ['None'], applications: ['Research', 'Creating heavier elements', 'Studying chemical properties', 'Academic research', 'Nuclear physics'] },
    { number: 102, symbol: 'No', name: 'Nobelium', mass: 259, category: 'actinide', electronegativity: 1.3, atomicRadius: 186, ionizationEnergy: 6.65, meltingPoint: 827, boilingPoint: null, electronConfig: '[Rn] 5f¹⁴ 7s²', shells: [2, 8, 18, 32, 32, 8, 2], hybridization: ['None'], applications: ['Research', 'Scientific studies', 'Creating heavier elements', 'Nuclear physics', 'Academic research'] },
    { number: 103, symbol: 'Lr', name: 'Lawrencium', mass: 266, category: 'actinide', electronegativity: 1.3, atomicRadius: 186, ionizationEnergy: 4.9, meltingPoint: 1627, boilingPoint: null, electronConfig: '[Rn] 5f¹⁴ 7s² 7p¹', shells: [2, 8, 18, 32, 32, 8, 3], hybridization: ['None'], applications: ['Research', 'Scientific studies', 'Creating heavier elements', 'Nuclear physics', 'Academic research'] },
    
    // Transactinides (104-118)
    { number: 104, symbol: 'Rf', name: 'Rutherfordium', mass: 267, category: 'transition-metal', electronegativity: null, atomicRadius: null, ionizationEnergy: 6, meltingPoint: 2100, boilingPoint: 5800, electronConfig: '[Rn] 5f¹⁴ 6d² 7s²', shells: [2, 8, 18, 32, 32, 10, 2], hybridization: ['None'], applications: ['Research', 'Scientific studies', 'Nuclear physics', 'Academic research', 'Creating heavier elements'] },
    { number: 105, symbol: 'Db', name: 'Dubnium', mass: 268, category: 'transition-metal', electronegativity: null, atomicRadius: null, ionizationEnergy: null, meltingPoint: null, boilingPoint: null, electronConfig: '[Rn] 5f¹⁴ 6d³ 7s²', shells: [2, 8, 18, 32, 32, 11, 2], hybridization: ['None'], applications: ['Research', 'Scientific studies', 'Nuclear physics', 'Academic research', 'Creating heavier elements'] },
    { number: 106, symbol: 'Sg', name: 'Seaborgium', mass: 269, category: 'transition-metal', electronegativity: null, atomicRadius: null, ionizationEnergy: null, meltingPoint: null, boilingPoint: null, electronConfig: '[Rn] 5f¹⁴ 6d⁴ 7s²', shells: [2, 8, 18, 32, 32, 12, 2], hybridization: ['None'], applications: ['Research', 'Scientific studies', 'Nuclear physics', 'Academic research', 'Creating heavier elements'] },
    { number: 107, symbol: 'Bh', name: 'Bohrium', mass: 270, category: 'transition-metal', electronegativity: null, atomicRadius: null, ionizationEnergy: null, meltingPoint: null, boilingPoint: null, electronConfig: '[Rn] 5f¹⁴ 6d⁵ 7s²', shells: [2, 8, 18, 32, 32, 13, 2], hybridization: ['None'], applications: ['Research', 'Scientific studies', 'Nuclear physics', 'Academic research', 'Creating heavier elements'] },
    { number: 108, symbol: 'Hs', name: 'Hassium', mass: 277, category: 'transition-metal', electronegativity: null, atomicRadius: null, ionizationEnergy: null, meltingPoint: null, boilingPoint: null, electronConfig: '[Rn] 5f¹⁴ 6d⁶ 7s²', shells: [2, 8, 18, 32, 32, 14, 2], hybridization: ['None'], applications: ['Research', 'Scientific studies', 'Nuclear physics', 'Academic research', 'Creating heavier elements'] },
    { number: 109, symbol: 'Mt', name: 'Meitnerium', mass: 278, category: 'unknown', electronegativity: null, atomicRadius: null, ionizationEnergy: null, meltingPoint: null, boilingPoint: null, electronConfig: '[Rn] 5f¹⁴ 6d⁷ 7s²', shells: [2, 8, 18, 32, 32, 15, 2], hybridization: ['None'], applications: ['Research', 'Scientific studies', 'Nuclear physics', 'Academic research', 'Creating heavier elements'] },
    { number: 110, symbol: 'Ds', name: 'Darmstadtium', mass: 281, category: 'unknown', electronegativity: null, atomicRadius: null, ionizationEnergy: null, meltingPoint: null, boilingPoint: null, electronConfig: '[Rn] 5f¹⁴ 6d⁸ 7s²', shells: [2, 8, 18, 32, 32, 16, 2], hybridization: ['None'], applications: ['Research', 'Scientific studies', 'Nuclear physics', 'Academic research', 'Creating heavier elements'] },
    { number: 111, symbol: 'Rg', name: 'Roentgenium', mass: 282, category: 'unknown', electronegativity: null, atomicRadius: null, ionizationEnergy: null, meltingPoint: null, boilingPoint: null, electronConfig: '[Rn] 5f¹⁴ 6d⁹ 7s²', shells: [2, 8, 18, 32, 32, 17, 2], hybridization: ['None'], applications: ['Research', 'Scientific studies', 'Nuclear physics', 'Academic research', 'Creating heavier elements'] },
    { number: 112, symbol: 'Cn', name: 'Copernicium', mass: 285, category: 'transition-metal', electronegativity: null, atomicRadius: null, ionizationEnergy: null, meltingPoint: null, boilingPoint: null, electronConfig: '[Rn] 5f¹⁴ 6d¹⁰ 7s²', shells: [2, 8, 18, 32, 32, 18, 2], hybridization: ['None'], applications: ['Research', 'Scientific studies', 'Nuclear physics', 'Academic research', 'Creating heavier elements'] },
    { number: 113, symbol: 'Nh', name: 'Nihonium', mass: 286, category: 'unknown', electronegativity: null, atomicRadius: null, ionizationEnergy: null, meltingPoint: null, boilingPoint: null, electronConfig: '[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p¹', shells: [2, 8, 18, 32, 32, 18, 3], hybridization: ['None'], applications: ['Research', 'Scientific studies', 'Nuclear physics', 'Academic research', 'Creating heavier elements'] },
    { number: 114, symbol: 'Fl', name: 'Flerovium', mass: 289, category: 'post-transition', electronegativity: null, atomicRadius: null, ionizationEnergy: null, meltingPoint: null, boilingPoint: null, electronConfig: '[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p²', shells: [2, 8, 18, 32, 32, 18, 4], hybridization: ['None'], applications: ['Research', 'Scientific studies', 'Nuclear physics', 'Academic research', 'Creating heavier elements'] },
    { number: 115, symbol: 'Mc', name: 'Moscovium', mass: 290, category: 'unknown', electronegativity: null, atomicRadius: null, ionizationEnergy: null, meltingPoint: null, boilingPoint: null, electronConfig: '[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p³', shells: [2, 8, 18, 32, 32, 18, 5], hybridization: ['None'], applications: ['Research', 'Scientific studies', 'Nuclear physics', 'Academic research', 'Creating heavier elements'] },
    { number: 116, symbol: 'Lv', name: 'Livermorium', mass: 293, category: 'unknown', electronegativity: null, atomicRadius: null, ionizationEnergy: null, meltingPoint: null, boilingPoint: null, electronConfig: '[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p⁴', shells: [2, 8, 18, 32, 32, 18, 6], hybridization: ['None'], applications: ['Research', 'Scientific studies', 'Nuclear physics', 'Academic research', 'Creating heavier elements'] },
    { number: 117, symbol: 'Ts', name: 'Tennessine', mass: 294, category: 'unknown', electronegativity: null, atomicRadius: null, ionizationEnergy: null, meltingPoint: null, boilingPoint: null, electronConfig: '[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p⁵', shells: [2, 8, 18, 32, 32, 18, 7], hybridization: ['None'], applications: ['Research', 'Scientific studies', 'Nuclear physics', 'Academic research', 'Creating heavier elements'] },
    { number: 118, symbol: 'Og', name: 'Oganesson', mass: 294, category: 'unknown', electronegativity: null, atomicRadius: null, ionizationEnergy: null, meltingPoint: null, boilingPoint: null, electronConfig: '[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p⁶', shells: [2, 8, 18, 32, 32, 18, 8], hybridization: ['None'], applications: ['Research', 'Scientific studies', 'Nuclear physics', 'Academic research', 'Creating heavier elements'] }
];

// Layout of the periodic table (element numbers or null for empty spaces)
const tableLayout = [
    [1, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 2],
    [3, 4, null, null, null, null, null, null, null, null, null, null, 5, 6, 7, 8, 9, 10],
    [11, 12, null, null, null, null, null, null, null, null, null, null, 13, 14, 15, 16, 17, 18],
    [19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36],
    [37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54],
    [55, 56, null, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86],
    [87, 88, null, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118],
    [null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null],
    [null, null, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, null],
    [null, null, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, null]
];

// Calculate min and max values for property visualizations
const electronegativityValues = elements.map(el => el.electronegativity).filter(val => val !== null);
const minElectronegativity = Math.min(...electronegativityValues);
const maxElectronegativity = Math.max(...electronegativityValues);

const atomicRadiusValues = elements.map(el => el.atomicRadius).filter(val => val !== null);
const minAtomicRadius = Math.min(...atomicRadiusValues);
const maxAtomicRadius = Math.max(...atomicRadiusValues);

const ionizationValues = elements.map(el => el.ionizationEnergy).filter(val => val !== null);
const minIonizationEnergy = Math.min(...ionizationValues);
const maxIonizationEnergy = Math.max(...ionizationValues);
